import { createMsdfAtlasCache, type MsdfAtlasCache } from "./msdf-atlas-cache.js";

/**
 * The process-wide default MSDF atlas cache every render-data entry point
 * (`prepareTextRenderData`, `prepareParagraphRenderData`) uses unless a
 * caller injects its own (e.g. for test isolation): one shared instance so
 * a font atlased through either entry point is never regenerated by the
 * other.
 */
export const sharedAtlasCache: MsdfAtlasCache = createMsdfAtlasCache();
